# Generated by Django 5.0.6 on 2024-05-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
