# Generated by Django 5.0.6 on 2024-05-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
